import type {
  PartnerOrder,
  MenuItem,
  MenuCategory,
  ModifierGroup,
  RestaurantProfile,
  Review,
  Notification,
  PromoPlacement,
  PushCampaign,
  SearchBoostSubscription,
  BadgePurchase,
} from '@/types'

// ===== Заказы =====

export const MOCK_ORDERS: PartnerOrder[] = [
  {
    id: 'ord-001',
    orderNumber: 1042,
    status: 'incoming',
    orderType: 'delivery',
    customer: { name: 'Ахмед Магомедов', address: 'пр. Кадырова 15, кв. 42', phone: '+7 (938) 111-22-33', floor: '5', apartment: '42' },
    items: [
      { name: 'Хинкали (10 шт)', quantity: 1, price: 450 },
      { name: 'Хачапури по-аджарски', quantity: 1, price: 380 },
      { name: 'Лимонад Тархун', quantity: 2, price: 150 },
    ],
    itemsCount: 4,
    totalPrice: 1130,
    deliveryFee: 100,
    createdAt: new Date(Date.now() - 3 * 60000).toISOString(),
  },
  {
    id: 'ord-002',
    orderNumber: 1043,
    status: 'incoming',
    orderType: 'pickup',
    customer: { name: 'Мадина Исаева', address: 'ул. Маяковского 8, кв. 15', phone: '+7 (938) 222-33-44', floor: '3', apartment: '15' },
    items: [
      { name: 'Шашлык из баранины', quantity: 2, price: 520 },
      { name: 'Салат Оливье', quantity: 1, price: 280 },
    ],
    itemsCount: 3,
    totalPrice: 1320,
    deliveryFee: 100,
    createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 'ord-003',
    orderNumber: 1041,
    status: 'preparing',
    orderType: 'delivery',
    customer: { name: 'Руслан Кадыров', address: 'ул. Первомайская 22', phone: '+7 (938) 333-44-55' },
    items: [
      { name: 'Чебуреки (3 шт)', quantity: 1, price: 300 },
      { name: 'Борщ', quantity: 1, price: 350 },
      { name: 'Хлеб лаваш', quantity: 2, price: 80 },
    ],
    itemsCount: 4,
    totalPrice: 810,
    deliveryFee: 100,
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    acceptedAt: new Date(Date.now() - 12 * 60000).toISOString(),
  },
  {
    id: 'ord-004',
    orderNumber: 1040,
    status: 'preparing',
    orderType: 'dine_in',
    customer: { name: 'Зарема Хасанова', address: 'пр. Путина 50, кв. 7', phone: '+7 (938) 444-55-66', floor: '2', apartment: '7', comment: 'Позвонить за 5 минут' },
    items: [
      { name: 'Пицца Маргарита', quantity: 1, price: 450 },
      { name: 'Пицца Пепперони', quantity: 1, price: 520 },
      { name: 'Кола 0.5л', quantity: 2, price: 120 },
    ],
    itemsCount: 4,
    totalPrice: 1210,
    deliveryFee: 0,
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
    acceptedAt: new Date(Date.now() - 22 * 60000).toISOString(),
  },
  {
    id: 'ord-005',
    orderNumber: 1039,
    status: 'ready',
    orderType: 'delivery',
    customer: { name: 'Ибрагим Дудаев', address: 'ул. Ленина 3, кв. 88', phone: '+7 (938) 555-66-77', floor: '9', apartment: '88' },
    items: [
      { name: 'Люля-кебаб', quantity: 2, price: 380 },
      { name: 'Рис с овощами', quantity: 1, price: 250 },
    ],
    itemsCount: 3,
    totalPrice: 1010,
    deliveryFee: 100,
    createdAt: new Date(Date.now() - 40 * 60000).toISOString(),
    acceptedAt: new Date(Date.now() - 37 * 60000).toISOString(),
    readyAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 'ord-006',
    orderNumber: 1038,
    status: 'completed',
    orderType: 'delivery',
    customer: { name: 'Амина Сулейманова', address: 'ул. Гагарина 12', phone: '+7 (938) 666-77-88' },
    items: [
      { name: 'Харчо', quantity: 1, price: 380 },
      { name: 'Хинкали (5 шт)', quantity: 1, price: 250 },
    ],
    itemsCount: 2,
    totalPrice: 630,
    deliveryFee: 100,
    createdAt: new Date(Date.now() - 120 * 60000).toISOString(),
    acceptedAt: new Date(Date.now() - 117 * 60000).toISOString(),
    readyAt: new Date(Date.now() - 90 * 60000).toISOString(),
    completedAt: new Date(Date.now() - 80 * 60000).toISOString(),
  },
  {
    id: 'ord-007',
    orderNumber: 1037,
    status: 'completed',
    orderType: 'pickup',
    customer: { name: 'Хасан Мусаев', address: 'пр. Кадырова 77', phone: '+7 (938) 777-88-99' },
    items: [
      { name: 'Долма (8 шт)', quantity: 1, price: 420 },
      { name: 'Чай зелёный', quantity: 2, price: 100 },
    ],
    itemsCount: 3,
    totalPrice: 620,
    deliveryFee: 100,
    createdAt: new Date(Date.now() - 180 * 60000).toISOString(),
    acceptedAt: new Date(Date.now() - 177 * 60000).toISOString(),
    readyAt: new Date(Date.now() - 150 * 60000).toISOString(),
    completedAt: new Date(Date.now() - 140 * 60000).toISOString(),
  },
  {
    id: 'ord-008',
    orderNumber: 1036,
    status: 'rejected',
    orderType: 'delivery',
    customer: { name: 'Лейла Абдулаева', address: 'ул. Мира 5', phone: '+7 (938) 888-99-00' },
    items: [
      { name: 'Стейк рибай', quantity: 1, price: 1200 },
    ],
    itemsCount: 1,
    totalPrice: 1200,
    deliveryFee: 100,
    createdAt: new Date(Date.now() - 200 * 60000).toISOString(),
    rejectedAt: new Date(Date.now() - 198 * 60000).toISOString(),
    rejectReason: 'Позиция закончилась',
  },
  {
    id: 'ord-009',
    orderNumber: 1035,
    status: 'completed',
    orderType: 'pickup',
    customer: { name: 'Магомед Алиев', address: 'ул. Чернышевского 18, кв. 3', phone: '+7 (938) 999-00-11' },
    items: [
      { name: 'Шаурма куриная', quantity: 2, price: 280 },
      { name: 'Картофель фри', quantity: 1, price: 180 },
      { name: 'Айран 0.5л', quantity: 2, price: 80 },
    ],
    itemsCount: 5,
    totalPrice: 900,
    deliveryFee: 0,
    createdAt: new Date(Date.now() - 300 * 60000).toISOString(),
    acceptedAt: new Date(Date.now() - 297 * 60000).toISOString(),
    readyAt: new Date(Date.now() - 275 * 60000).toISOString(),
    completedAt: new Date(Date.now() - 260 * 60000).toISOString(),
  },
  {
    id: 'ord-010',
    orderNumber: 1034,
    status: 'completed',
    orderType: 'dine_in',
    customer: { name: 'Патимат Гамзатова', address: 'пр. Победы 33', phone: '+7 (938) 000-11-22' },
    items: [
      { name: 'Суп-пюре грибной', quantity: 1, price: 320 },
      { name: 'Цезарь с курицей', quantity: 1, price: 380 },
      { name: 'Чай чёрный', quantity: 1, price: 100 },
    ],
    itemsCount: 3,
    totalPrice: 800,
    deliveryFee: 100,
    createdAt: new Date(Date.now() - 400 * 60000).toISOString(),
    acceptedAt: new Date(Date.now() - 397 * 60000).toISOString(),
    readyAt: new Date(Date.now() - 370 * 60000).toISOString(),
    completedAt: new Date(Date.now() - 355 * 60000).toISOString(),
  },
]

// ===== Категории меню =====

export const MOCK_CATEGORIES: MenuCategory[] = [
  { id: 1, name: 'Выпечка', sortOrder: 1 },
  { id: 2, name: 'Горячее', sortOrder: 2 },
  { id: 3, name: 'Супы', sortOrder: 3 },
  { id: 4, name: 'Напитки', sortOrder: 4 },
]

// ===== Позиции меню =====

export const MOCK_MENU_ITEMS: MenuItem[] = [
  // Выпечка
  { id: 1, name: 'Хачапури по-аджарски', description: 'Традиционное грузинское блюдо с сыром и яйцом', price: 380, category: 1, available: true, weight: 350, image: 'https://img.freepik.com/free-photo/khachapuri-with-egg-plate_140725-5765.jpg?w=740', nutrition: { calories: 450, protein: 18, fat: 22, carbs: 42 }, allergens: ['gluten', 'dairy', 'eggs'], modifierGroups: [], sortOrder: 1 },
  { id: 2, name: 'Чебуреки (3 шт)', description: 'Хрустящие чебуреки с мясной начинкой', price: 300, category: 1, available: true, weight: 300, nutrition: { calories: 520, protein: 22, fat: 28, carbs: 44 }, allergens: ['gluten'], modifierGroups: [1], sortOrder: 2 },
  { id: 3, name: 'Хлеб лаваш', description: 'Свежий тонкий лаваш', price: 80, category: 1, available: true, weight: 150, allergens: ['gluten'], modifierGroups: [], sortOrder: 3 },

  // Горячее
  { id: 4, name: 'Шашлык из баранины', description: 'Сочный шашлык из отборной баранины на углях', price: 520, category: 2, available: true, weight: 300, image: 'https://img.freepik.com/free-photo/side-view-kebab-with-grilled-vegetables-sliced-onion-plate_141793-4882.jpg?w=740', nutrition: { calories: 380, protein: 32, fat: 24, carbs: 2 }, allergens: [], modifierGroups: [2], sortOrder: 1 },
  { id: 5, name: 'Люля-кебаб', description: 'Ароматный кебаб из рубленого мяса со специями', price: 380, category: 2, available: true, weight: 250, nutrition: { calories: 340, protein: 28, fat: 20, carbs: 8 }, allergens: [], modifierGroups: [2], sortOrder: 2 },
  { id: 6, name: 'Хинкали (10 шт)', description: 'Грузинские пельмени с ароматным бульоном внутри', price: 450, category: 2, available: true, weight: 500, nutrition: { calories: 480, protein: 24, fat: 18, carbs: 52 }, allergens: ['gluten'], modifierGroups: [1], sortOrder: 3 },
  { id: 7, name: 'Долма (8 шт)', description: 'Виноградные листья с начинкой из мяса и риса', price: 420, category: 2, available: false, weight: 400, allergens: [], modifierGroups: [], sortOrder: 4 },

  // Супы
  { id: 8, name: 'Харчо', description: 'Острый грузинский суп с говядиной и рисом', price: 380, category: 3, available: true, weight: 350, nutrition: { calories: 280, protein: 18, fat: 12, carbs: 28 }, allergens: ['nuts'], modifierGroups: [3], sortOrder: 1 },
  { id: 9, name: 'Борщ', description: 'Классический борщ со сметаной', price: 350, category: 3, available: true, weight: 350, nutrition: { calories: 220, protein: 12, fat: 8, carbs: 30 }, allergens: ['dairy'], modifierGroups: [3], sortOrder: 2 },
  { id: 10, name: 'Суп-пюре грибной', description: 'Нежный крем-суп из белых грибов', price: 320, category: 3, available: true, weight: 300, allergens: ['dairy'], modifierGroups: [3], sortOrder: 3 },

  // Напитки
  { id: 11, name: 'Лимонад Тархун', description: 'Домашний лимонад с тархуном', price: 150, category: 4, available: true, weight: 400, allergens: [], modifierGroups: [], sortOrder: 1 },
  { id: 12, name: 'Чай зелёный', description: 'Листовой зелёный чай', price: 100, category: 4, available: true, weight: 300, allergens: [], modifierGroups: [], sortOrder: 2 },
  { id: 13, name: 'Чай чёрный', description: 'Листовой чёрный чай с чабрецом', price: 100, category: 4, available: true, weight: 300, allergens: [], modifierGroups: [], sortOrder: 3 },
  { id: 14, name: 'Айран 0.5л', description: 'Традиционный кисломолочный напиток', price: 80, category: 4, available: true, weight: 500, allergens: ['dairy'], modifierGroups: [], sortOrder: 4 },
]

// ===== Группы модификаторов =====

export const MOCK_MODIFIER_GROUPS: ModifierGroup[] = [
  {
    id: 1,
    name: 'Начинка',
    required: false,
    maxSelect: 2,
    modifiers: [
      { id: 1, name: 'Мясо', price: 0 },
      { id: 2, name: 'Сыр', price: 50 },
      { id: 3, name: 'Картофель', price: 30 },
    ],
  },
  {
    id: 2,
    name: 'Размер порции',
    required: true,
    maxSelect: 1,
    modifiers: [
      { id: 4, name: 'Стандарт', price: 0 },
      { id: 5, name: 'Большая (+50%)', price: 150 },
      { id: 6, name: 'Двойная', price: 280 },
    ],
  },
  {
    id: 3,
    name: 'Дополнительно к супу',
    required: false,
    maxSelect: 3,
    modifiers: [
      { id: 7, name: 'Сметана', price: 30 },
      { id: 8, name: 'Сухарики', price: 40 },
      { id: 9, name: 'Зелень', price: 20 },
    ],
  },
]

// ===== Профиль ресторана =====

export const MOCK_RESTAURANT: RestaurantProfile = {
  id: 'rest-001',
  name: 'Тбилисо',
  description: 'Ресторан грузинской кухни. Традиционные блюда, приготовленные по семейным рецептам с использованием свежих продуктов.',
  address: 'пр. Кадырова 30',
  phone: '+7 (938) 000-00-01',
  coverImage: 'https://img.freepik.com/free-photo/top-view-table-full-delicious-food-composition_23-2149141353.jpg?w=1380',
  rating: 4.7,
  reviewsCount: 253,
  isOpen: true,
  workingHours: {
    monday: { open: '10:00', close: '23:00', isOpen: true },
    tuesday: { open: '10:00', close: '23:00', isOpen: true },
    wednesday: { open: '10:00', close: '23:00', isOpen: true },
    thursday: { open: '10:00', close: '23:00', isOpen: true },
    friday: { open: '10:00', close: '00:00', isOpen: true },
    saturday: { open: '11:00', close: '00:00', isOpen: true },
    sunday: { open: '11:00', close: '22:00', isOpen: true },
  },
  deliveryTime: '35-40',
  minOrderAmount: 500,
  cuisineTypes: ['Грузинская', 'Кавказская', 'Европейская'],
}

// ===== Отзывы =====

export const MOCK_REVIEWS: Review[] = [
  {
    id: 1,
    author: 'Мария Сулейманова',
    rating: 5,
    text: 'Очень вкусная еда! Хычины просто объедение — хрустящие, с ароматной начинкой. Доставили быстро, всё было горячим. Обязательно закажу ещё!',
    date: new Date(Date.now() - 2 * 86400000).toISOString(),
    orderType: 'delivery',
    orderNumber: 1038,
    items: ['Хачапури по-аджарски', 'Хинкали (10 шт)'],
    reply: 'Спасибо за тёплые слова, Мария! Рады, что вам понравилось. Ждём вас снова!',
    repliedAt: new Date(Date.now() - 1.5 * 86400000).toISOString(),
  },
  {
    id: 2,
    author: 'Алексей Рустамов',
    rating: 4,
    text: 'Отличная кухня, быстрая доставка. Лобиани был горячим, как будто только из печи. Единственный минус — не положили соус, который заказывал.',
    date: new Date(Date.now() - 4 * 86400000).toISOString(),
    orderType: 'delivery',
    orderNumber: 1035,
    items: ['Люля-кебаб', 'Рис с овощами'],
    reply: 'Алексей, приносим извинения за соус! Передали на кухню, чтобы такое не повторялось. Спасибо за отзыв!',
    repliedAt: new Date(Date.now() - 3.5 * 86400000).toISOString(),
  },
  {
    id: 3,
    author: 'Диана Казбекова',
    rating: 5,
    text: 'Заказывала харчо и хинкали — всё на высшем уровне. Порции большие, цена адекватная. Очень довольна!',
    date: new Date(Date.now() - 6 * 86400000).toISOString(),
    orderType: 'pickup',
    orderNumber: 1030,
    items: ['Харчо', 'Хинкали (10 шт)', 'Чай зелёный'],
  },
  {
    id: 4,
    author: 'Хасан Магомедов',
    rating: 3,
    text: 'Еда вкусная, но доставка заняла больше часа. Курьер не мог найти адрес. Хотелось бы, чтобы с логистикой стало лучше.',
    date: new Date(Date.now() - 8 * 86400000).toISOString(),
    orderType: 'delivery',
    orderNumber: 1025,
    items: ['Шашлык из баранины', 'Борщ'],
  },
  {
    id: 5,
    author: 'Амина Ахмедова',
    rating: 5,
    text: 'Лучший ресторан грузинской кухни в городе! Хачапури по-аджарски — это шедевр. Семья в восторге, заказываем каждые выходные.',
    date: new Date(Date.now() - 10 * 86400000).toISOString(),
    orderType: 'delivery',
    orderNumber: 1020,
    items: ['Хачапури по-аджарски', 'Долма (8 шт)', 'Лимонад Тархун'],
    reply: 'Амина, спасибо огромное! Очень приятно слышать такие слова. Готовим с душой для вас!',
    repliedAt: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
  {
    id: 6,
    author: 'Руслан Исмаилов',
    rating: 4,
    text: 'Пришёл с друзьями на обед. Атмосфера отличная, обслуживание быстрое. Чебуреки немного остыли, но в целом всё отлично.',
    date: new Date(Date.now() - 12 * 86400000).toISOString(),
    orderType: 'dine_in',
    orderNumber: 1015,
    items: ['Чебуреки (3 шт)', 'Шаурма куриная', 'Айран 0.5л'],
  },
  {
    id: 7,
    author: 'Патимат Гамзатова',
    rating: 5,
    text: 'Грибной суп-пюре невероятный! Такого нежного вкуса не пробовала нигде. Цезарь тоже на уровне. Буду рекомендовать друзьям.',
    date: new Date(Date.now() - 14 * 86400000).toISOString(),
    orderType: 'dine_in',
    orderNumber: 1034,
    items: ['Суп-пюре грибной', 'Цезарь с курицей'],
    reply: 'Патимат, благодарим за чудесный отзыв! Наш шеф будет рад!',
    repliedAt: new Date(Date.now() - 13 * 86400000).toISOString(),
  },
  {
    id: 8,
    author: 'Ибрагим Османов',
    rating: 2,
    text: 'Заказал стейк рибай, но получил не то, что ожидал. Мясо было жёстким и пережаренным. За такую цену хотелось бы лучшего качества.',
    date: new Date(Date.now() - 16 * 86400000).toISOString(),
    orderType: 'delivery',
    orderNumber: 1010,
    items: ['Стейк рибай'],
    reply: 'Ибрагим, искренне извиняемся! Мы разобрали ситуацию с кухней. Будем рады предложить вам комплимент при следующем заказе.',
    repliedAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 9,
    author: 'Зарема Даудова',
    rating: 5,
    text: 'Самовывоз — супер удобно! Всё было готово вовремя, упаковано аккуратно. Долма — отдельный вид искусства. Спасибо!',
    date: new Date(Date.now() - 18 * 86400000).toISOString(),
    orderType: 'pickup',
    orderNumber: 1005,
    items: ['Долма (8 шт)', 'Чай чёрный'],
  },
  {
    id: 10,
    author: 'Магомед Шамилев',
    rating: 4,
    text: 'Хорошее заведение с достойной кухней. Порции щедрые. Немного не хватает разнообразия в десертах, но основное меню — огонь.',
    date: new Date(Date.now() - 20 * 86400000).toISOString(),
    orderType: 'dine_in',
    orderNumber: 1000,
    items: ['Харчо', 'Шашлык из баранины', 'Лимонад Тархун'],
  },
  {
    id: 11,
    author: 'Лейла Абдурахманова',
    rating: 1,
    text: 'Ужасный опыт. Заказ пришёл через 2 часа, половина блюд холодная. Служба поддержки не отвечала. Больше не буду заказывать.',
    date: new Date(Date.now() - 22 * 86400000).toISOString(),
    orderType: 'delivery',
    orderNumber: 995,
    items: ['Пицца Маргарита', 'Пицца Пепперони', 'Кола 0.5л'],
    reply: 'Лейла, нам очень жаль, что вы столкнулись с такой ситуацией. Мы провели работу с командой доставки. Свяжитесь с нами — мы компенсируем заказ.',
    repliedAt: new Date(Date.now() - 21 * 86400000).toISOString(),
  },
  {
    id: 12,
    author: 'Саид Алханов',
    rating: 5,
    text: 'Постоянный клиент уже полгода. Качество не падает, всегда вкусно и свежо. Особенно люблю хинкали и харчо. Лучшие в городе!',
    date: new Date(Date.now() - 25 * 86400000).toISOString(),
    orderType: 'delivery',
    orderNumber: 990,
    items: ['Хинкали (10 шт)', 'Харчо'],
  },
]

// ===== Уведомления =====

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'ntf-001',
    type: 'new_order',
    title: 'Новый заказ #1045',
    message: 'Ахмед Магомедов — доставка, 1 250 ₽',
    createdAt: new Date(Date.now() - 2 * 60000).toISOString(),
    isRead: false,
    orderId: 'ord-001',
    orderNumber: 1045,
  },
  {
    id: 'ntf-002',
    type: 'new_review',
    title: 'Новый отзыв — 5 звёзд',
    message: 'Зарина Исаева: «Всё было очень вкусно, доставили быстро!»',
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    isRead: false,
    reviewId: 1,
  },
  {
    id: 'ntf-003',
    type: 'order_status',
    title: 'Заказ #1044 готов',
    message: 'Заказ ожидает курьера',
    createdAt: new Date(Date.now() - 35 * 60000).toISOString(),
    isRead: false,
    orderId: 'ord-002',
    orderNumber: 1044,
  },
  {
    id: 'ntf-004',
    type: 'order_rejected',
    title: 'Заказ #1043 отклонён',
    message: 'Причина: нет ингредиентов',
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    isRead: true,
    orderId: 'ord-003',
    orderNumber: 1043,
  },
  {
    id: 'ntf-005',
    type: 'new_order',
    title: 'Новый заказ #1042',
    message: 'Муса Хасанов — самовывоз, 780 ₽',
    createdAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    isRead: true,
    orderId: 'ord-004',
    orderNumber: 1042,
  },
  {
    id: 'ntf-006',
    type: 'new_review',
    title: 'Новый отзыв — 3 звезды',
    message: 'Рустам Алиев: «Ждал дольше обещанного, но еда хорошая»',
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    isRead: true,
    reviewId: 2,
  },
  {
    id: 'ntf-007',
    type: 'order_status',
    title: 'Заказ #1041 завершён',
    message: 'Заказ успешно доставлен клиенту',
    createdAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    isRead: true,
    orderId: 'ord-005',
    orderNumber: 1041,
  },
  {
    id: 'ntf-008',
    type: 'system',
    title: 'Заведение будет закрыто',
    message: 'Не забудьте изменить статус в настройках перед закрытием',
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    isRead: true,
  },
]

// ===== Продвижение =====

const day = 86400000

export const MOCK_PROMOTIONS: PromoPlacement[] = [
  {
    id: 'promo-001',
    slot: 'promo_banner',
    status: 'active',
    startDate: new Date(Date.now() - 5 * day).toISOString(),
    endDate: new Date(Date.now() + 9 * day).toISOString(),
    duration: 14,
    price: 11500,
    impressions: 18420,
    clicks: 743,
    createdAt: new Date(Date.now() - 5 * day).toISOString(),
  },
  {
    id: 'promo-002',
    slot: 'popular_brands',
    status: 'active',
    startDate: new Date(Date.now() - 3 * day).toISOString(),
    endDate: new Date(Date.now() + 11 * day).toISOString(),
    duration: 14,
    price: 6800,
    impressions: 9210,
    clicks: 312,
    createdAt: new Date(Date.now() - 3 * day).toISOString(),
  },
  {
    id: 'promo-003',
    slot: 'often_order',
    status: 'expired',
    startDate: new Date(Date.now() - 37 * day).toISOString(),
    endDate: new Date(Date.now() - 7 * day).toISOString(),
    duration: 14,
    price: 5200,
    impressions: 24500,
    clicks: 1120,
    createdAt: new Date(Date.now() - 37 * day).toISOString(),
  },
  {
    id: 'promo-004',
    slot: 'near_you',
    status: 'pending',
    startDate: new Date(Date.now() + 2 * day).toISOString(),
    endDate: new Date(Date.now() + 16 * day).toISOString(),
    duration: 14,
    price: 4500,
    impressions: 0,
    clicks: 0,
    createdAt: new Date(Date.now() - 1 * day).toISOString(),
  },
  {
    id: 'promo-005',
    slot: 'app_open_modal',
    status: 'active',
    startDate: new Date(Date.now() - 2 * day).toISOString(),
    endDate: new Date(Date.now() + 5 * day).toISOString(),
    duration: 7,
    price: 8300,
    impressions: 31200,
    clicks: 1580,
    createdAt: new Date(Date.now() - 2 * day).toISOString(),
  },
  {
    id: 'promo-006',
    slot: 'timed_popup',
    status: 'expired',
    startDate: new Date(Date.now() - 21 * day).toISOString(),
    endDate: new Date(Date.now() - 7 * day).toISOString(),
    duration: 14,
    price: 8400,
    impressions: 28900,
    clicks: 1240,
    createdAt: new Date(Date.now() - 21 * day).toISOString(),
  },
  {
    id: 'promo-007',
    slot: 'special_offers',
    status: 'active',
    startDate: new Date(Date.now() - 10 * day).toISOString(),
    endDate: new Date(Date.now() + 80 * day).toISOString(),
    duration: 90,
    price: 20520,
    impressions: 5400,
    clicks: 210,
    createdAt: new Date(Date.now() - 10 * day).toISOString(),
  },
]

// ===== Push-рассылки =====

export const MOCK_PUSH_CAMPAIGNS: PushCampaign[] = [
  {
    id: 'push-001',
    title: 'Скидка 20% на все блюда сегодня!',
    body: 'Только сегодня — скидка 20% на весь заказ от 600 ₽. Не упустите!',
    imageUrl: 'https://img.freepik.com/free-photo/top-view-assorted-food_1057-10075.jpg?w=740',
    audience: 'all',
    scheduleMode: 'now',
    status: 'sent',
    createdAt: new Date(Date.now() - 10 * day).toISOString(),
    sentAt: new Date(Date.now() - 10 * day).toISOString(),
    sent: 4820,
    delivered: 4601,
    opened: 1380,
    clicked: 412,
  },
  {
    id: 'push-002',
    title: 'Хинкали снова в наличии!',
    body: 'Ваши любимые хинкали вернулись в меню. Заказывайте прямо сейчас.',
    audience: 'recent',
    scheduleMode: 'now',
    status: 'sent',
    createdAt: new Date(Date.now() - 5 * day).toISOString(),
    sentAt: new Date(Date.now() - 5 * day).toISOString(),
    sent: 2310,
    delivered: 2198,
    opened: 876,
    clicked: 311,
  },
  {
    id: 'push-003',
    title: 'Мы скучаем по вам!',
    body: 'Давно не делали заказ? Возвращайтесь — подарок внутри!',
    audience: 'inactive',
    scheduleMode: 'now',
    status: 'sent',
    createdAt: new Date(Date.now() - 2 * day).toISOString(),
    sentAt: new Date(Date.now() - 2 * day).toISOString(),
    sent: 1090,
    delivered: 1012,
    opened: 540,
    clicked: 198,
  },
  {
    id: 'push-004',
    title: 'Пятничная акция — 2 по цене 1',
    body: 'Только в пятницу: закажи 2 хачапури — получи третий в подарок!',
    audience: 'all',
    scheduleMode: 'scheduled',
    scheduledAt: new Date(Date.now() + 3 * day).toISOString(),
    status: 'scheduled',
    createdAt: new Date(Date.now() - 1 * day).toISOString(),
    sent: 0,
    delivered: 0,
    opened: 0,
    clicked: 0,
  },
]

// ===== Буст в поиске =====

export const MOCK_BOOST_SUBSCRIPTIONS: SearchBoostSubscription[] = [
  {
    id: 'boost-001',
    level: 'pro',
    status: 'active',
    startDate: new Date(Date.now() - 4 * day).toISOString(),
    endDate: new Date(Date.now() + 10 * day).toISOString(),
    duration: 14,
    price: 8260,
    positionBefore: 34,
    positionAfter: 9,
    viewsGained: 1840,
    ordersGained: 23,
    createdAt: new Date(Date.now() - 4 * day).toISOString(),
  },
  {
    id: 'boost-002',
    level: 'standard',
    status: 'expired',
    startDate: new Date(Date.now() - 25 * day).toISOString(),
    endDate: new Date(Date.now() - 11 * day).toISOString(),
    duration: 14,
    price: 4060,
    positionBefore: 28,
    positionAfter: 18,
    viewsGained: 980,
    ordersGained: 11,
    createdAt: new Date(Date.now() - 25 * day).toISOString(),
  },
]

// ===== Бейдж «Рекомендуемое» =====

export const MOCK_BADGE_PURCHASES: BadgePurchase[] = [
  {
    id: 'badge-001',
    status: 'active',
    startDate: new Date(Date.now() - 6 * day).toISOString(),
    endDate: new Date(Date.now() + 8 * day).toISOString(),
    duration: 14,
    price: 5200,
    impressions: 12480,
    extraClicks: 340,
    conversionLift: 4.2,
    createdAt: new Date(Date.now() - 6 * day).toISOString(),
  },
  {
    id: 'badge-002',
    status: 'expired',
    startDate: new Date(Date.now() - 30 * day).toISOString(),
    endDate: new Date(Date.now() - 16 * day).toISOString(),
    duration: 14,
    price: 5200,
    impressions: 19600,
    extraClicks: 510,
    conversionLift: 5.8,
    createdAt: new Date(Date.now() - 30 * day).toISOString(),
  },
]
