/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoriesDialog: typeof import('./components/CategoriesDialog.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    MenuItemCard: typeof import('./components/MenuItemCard.vue')['default']
    MenuItemDialog: typeof import('./components/MenuItemDialog.vue')['default']
    ModifiersDialog: typeof import('./components/ModifiersDialog.vue')['default']
    OrderCard: typeof import('./components/OrderCard.vue')['default']
    OrderDetailsDialog: typeof import('./components/OrderDetailsDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDelivery: typeof import('./components/settings/SettingsDelivery.vue')['default']
    SettingsNotifications: typeof import('./components/settings/SettingsNotifications.vue')['default']
    SettingsProfile: typeof import('./components/settings/SettingsProfile.vue')['default']
    SettingsSchedule: typeof import('./components/settings/SettingsSchedule.vue')['default']
    SettingsSecurity: typeof import('./components/settings/SettingsSecurity.vue')['default']
    StatCard: typeof import('./components/StatCard.vue')['default']
    StatusBadge: typeof import('./components/StatusBadge.vue')['default']
  }
}
